// -=-=-= Portfolio Entries =-=-=-

let portfolioEntries = [
	{
		title: 'The Clockmaker',
		fileName: 'clockmaker',
		fileCount: 1,
		format: 'Illustration',
		sortedDate: '20221220',
		displayDate: 'December 20, 2022',
		url: '',
		description: 'Acrylic | 15x20in\n\nThis is a work that focuses on patterns and contrast. I also learned some adobe illustrator features along the way, including tiling.',
	},
	{
		title: 'Color Value Study',
		fileName: 'colorValueStudy',
		fileCount: 1,
		format: 'Illustration',
		sortedDate: '20220310',
		displayDate: 'March 10, 2022',
		url: '',
		description: 'Acrylic | 20x30 in\n\nA photograph of somebody I knew was observed by value. I then assigned a color to each value, matched by relative value. I then simply painted that selection.',
	},
	{
		title: 'Still Life',
		fileName: 'stillLife',
		fileCount: 1,
		format: 'Illustration',
		sortedDate: '20221123',
		displayDate: 'November 23, 2022',
		url: '',
		description: 'Colored Pencil | 13.5x11 in\n\nI wanted to capture several objects that represent who I am. These objects are things I wear, and what I need to be me. I wanted to experiment with colored pencil as well, so colored shading was used there.',
	},
	{
		title: 'Showtime',
		fileName: 'showtime3d',
		fileCount: 3,
		format: 'Illustration',
		sortedDate: '20220429',
		displayDate: 'April 29, 2022',
		url: '',
		description: 'Digital 3D Model | 1080x1920 px\n\nThis was during my learning times of figuring out how to model in 3D. This means that the model itself isn’t even that good. The lighting was purely accidental, but I turned it into a stage scene.',
	},
	{
		title: 'Design and Visual Communications Banner',
		fileName: 'dvcBanner',
		fileCount: 2,
		format: 'Illustration',
		sortedDate: '20220101',
		displayDate: '2022',
		url: '',
		description: 'Digital/Banner Material | 18x48 in\n\nThis is a design of the stanchion poster for Keefe Tech’s Design and Visual Communications shop. Each square represents the elements of design.\n\nThis banner was actually selected to be the base for the designs of the other shops. I only made the Design and Visual banner, everything else was made by others.',
	},
	{
		title: 'Forest',
		fileName: 'forest',
		fileCount: 1,
		format: 'Illustration',
		sortedDate: '20220405',
		displayDate: 'April 5, 2022',
		url: '',
		description: 'Ever wanted to see a bunch of shapes? Wanted to see atmospheric depth? Well I tried.',
	},
	{
		title: 'Self Portrait (2022)',
		fileName: 'selfPortrait22',
		fileCount: 1,
		format: 'Video',
		sortedDate: '20221026',
		displayDate: 'October 26, 2022',
		url: 'https://youtu.be/HGneardwIkw',
		description: 'Pen/Digital/Photography | 6000x4000 px (Original Video)\n\nI created this self portrait in a way that tells people that I like to explore who I am. I\ntried doing it in a fun way where I make who I am.',
	},
	{
		title: 'Master Study: Hiroshige',
		fileName: 'hiroshigeStudy',
		fileCount: 1,
		format: 'Illustration',
		sortedDate: '20220101',
		displayDate: '2022-2023',
		url: '',
		description: 'Printmaking/Ink | 10x8 in\n\nI used print making to create this piece. I sliced a\nlinoleum block to recreate a piece by the Ukiyo-e artist, Hiroshige.',
	},
	{
		title: 'Quick Links Semester 1',
		fileName: 'quickLinksSem1',
		fileCount: 1,
		format: 'Programming Project',
		sortedDate: '20230101',
		displayDate: 'January 1, 2023',
		url: 'https://starshinec.github.io/quicklinks-semester-1-ver-portfolio/',
		description: 'This is a personal quick links page I made for myself in my first semester in order to access links for my classes quickly. This was simply practice for web design, alongside being a convenient way for me to view everything easily.\n\nThe included weblink actually isn’t the real thing. For privacy purposes, I’ve removed all of the actual weblinks for the portfolio version.',
	},
	{
		title: 'Stereoscopic 3D Test',
		fileName: 'stereo3Dtest',
		fileCount: 1,
		format: 'Video',
		sortedDate: '20240626',
		displayDate: 'June 26, 2024',
		url: 'https://youtu.be/ME8ebLkcs58',
		description: 'This is a small project made in preparation for another planned short film project. I wanted to try out stereoscopic 3D, and while the result ended up being more shallow than I was hoping for, the effect was still successful. I was able to learn more about the 3D modeling program Blender, including the rendering options, how lights work, how to use image sequences, and some applications Blender has with 2D animation.',
	},
	{
		title: 'LineType',
		fileName: 'lineType',
		fileCount: 1,
		format: 'Video',
		sortedDate: '20221011',
		displayDate: 'October 11, 2022',
		url: 'https://youtu.be/b8KV2QqGJT0?si=ikMYOvsxJeoPO7fY',
		description: 'This is a tutorial for people who don’t know how the lines in adobe products work. I\ntried styling this as an old instructional video for school children. Most of the assets used aren’t actually mine. I found them in free-to-use websites, including the music.',
	},
	{
		title: 'Hope',
		fileName: 'hope',
		fileCount: 1,
		format: 'Video',
		sortedDate: '20220408',
		displayDate: 'April 8, 2022',
		url: 'https://youtu.be/ME8ebLkcs58',
		description: 'This is my short film submission for the Metrowest Student Film Festival of 2022 in the animation category. I was actually able to get in the finals with this film, even with the fact that I made this film with Flipnote Studio 3D for the Nintendo 3DS.',
	},
	{
		title: 'New Friend',
		fileName: 'newFriend',
		fileCount: 1,
		format: 'Video',
		sortedDate: '20230406',
		displayDate: 'April 6, 2023',
		url: ' https://youtu.be/vAhHAOvCKkM',
		description: 'This is my short film submission for the Metrowest Student Film Festival of 2023 in the animation category. I also wanted to do this one on the 3DS (See Hope), but I ultimately decided on using Clip Studio Paint instead. I also got to dabble in compositing for special lighting effects and enhanced motion.',
	},
	{
		title: 'Personal Website',
		fileName: 'personalWebsite',
		fileCount: 0,
		format: 'Programming Project',
		sortedDate: '20240807',
		displayDate: 'August 7, 2024',
		url: 'starshinec.github.io',
		description: 'This is the website you are viewing right now! What do you think? This project is here because I wanted some practice in frontend styling and filtering, but there’s actually quite a bit more on my end than usual. I actually made a python script to resize, rename, and reformat all the portfolio image files used, and another to generate a JavaScript file with a dictionary from a csv file created from a Notion database. I’ve decided to include that on a separate branch on the repository, if you’d like to view that.',
	},
	{
		title: 'Penguin and Penguin',
		fileName: 'penguinAndPenguin',
		fileCount: 2,
		format: 'Illustration',
		sortedDate: '20220101',
		displayDate: '2022-2023',
		url: '',
		description: 'Watercolor, Paper | 8.5x11 in.\n\n2 Penguins were walking amongst colorful terrain. One can see color, the other is\ncolor. Both are examples of the use of negative space.',
	},
	{
		title: 'Windmill',
		fileName: 'windmillx2',
		fileCount: 2,
		format: 'Illustration',
		sortedDate: '20220101',
		displayDate: '2022',
		url: '',
		description: 'Watercolor/Acryllic | 9x12 in\n\nA windmill is on the street, and it’s collecting wind to assist the farm. With a reference photograph, I actually did this piece twice in 2 separate mediums. I did it in watercolor to see how layering colors worked, and in acrylic to see how it compared to the watercolor piece.',
	}
]